2022-10-11 03:49:51,467 INFO    Thread-8  :23483 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 03:49:51,467 INFO    Thread-8  :23483 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 03:49:51,467 INFO    Thread-8  :23483 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'run_id': 'g3ugp4b4', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-ivsfe5pd/config-g3ugp4b4.yaml', 'sweep_id': 'ivsfe5pd'}
2022-10-11 03:49:51,467 INFO    Thread-8  :23483 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 03:49:51,467 INFO    Thread-8  :23483 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_034951-g3ugp4b4/logs/debug.log
2022-10-11 03:49:51,467 INFO    Thread-8  :23483 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_034951-g3ugp4b4/logs/debug-internal.log
2022-10-11 03:49:51,467 INFO    Thread-8  :23483 [wandb_init.py:init():439] calling init triggers
2022-10-11 03:49:51,468 INFO    Thread-8  :23483 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 56, 'dropout': 0.5, 'epochs': 1, 'hidden_size': 256, 'learning_rate': 0.02858948923241418, 'optimizer': 'adam'}
config: {}
2022-10-11 03:49:51,468 INFO    Thread-8  :23483 [wandb_init.py:init():492] starting backend
2022-10-11 03:49:51,468 INFO    Thread-8  :23483 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 03:49:51,472 INFO    Thread-8  :23483 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 03:49:51,512 INFO    Thread-8  :23483 [backend.py:ensure_launched():225] started backend process with pid: 24236
2022-10-11 03:49:51,514 INFO    Thread-8  :23483 [wandb_init.py:init():501] backend started and connected
2022-10-11 03:49:51,522 INFO    Thread-8  :23483 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 56, 'dropout': 0.5, 'epochs': 1, 'hidden_size': 256, 'learning_rate': 0.02858948923241418, 'optimizer': 'adam'}
2022-10-11 03:49:51,529 INFO    Thread-8  :23483 [wandb_init.py:init():565] updated telemetry
2022-10-11 03:49:51,628 INFO    Thread-8  :23483 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 03:49:52,594 INFO    Thread-8  :23483 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 03:49:52,634 INFO    Thread-8  :23483 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 03:49:52,634 INFO    Thread-8  :23483 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 03:49:55,554 INFO    Thread-8  :23483 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 03:49:55,555 INFO    Thread-8  :23483 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 03:49:55,555 INFO    Thread-8  :23483 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 03:49:55,555 ERROR   Thread-8  :23483 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 03:49:55,556 INFO    Thread-8  :23483 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 03:49:55,556 INFO    Thread-8  :23483 [wandb_run.py:_config_callback():992] config_cb None None {'img_feature_path': 'data/features/visualbert/', 'train_csv_path': 'data/splits/random/memotion_train.csv', 'val_csv_path': 'data/splits/random/memotion_val.csv', 'model_type': 'visualbert', 'model_path': 'uclanlp/visualbert-nlvr2-coco-pre', 'eval_step': 100, 'amp': True, 'output_dir': './tmp', 'checkpoint_step': 100, 'random_seed': 42, 'resume_training': False, 'semi_supervised': False}
2022-10-11 03:49:55,926 INFO    Thread-8  :23483 [wandb_run.py:_config_callback():992] config_cb None None {'output_hidden': 768}
2022-10-11 03:51:19,407 INFO    Thread-8  :23483 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/g3ugp4b4
2022-10-11 03:51:19,408 INFO    Thread-8  :23483 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-10-11 03:51:19,410 INFO    Thread-8  :23483 [wandb_run.py:_restore():1674] restore
2022-10-11 03:51:19,414 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 03:51:19,664 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 03:51:20,643 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 9283
}

2022-10-11 03:51:20,745 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 10605
}

2022-10-11 03:51:20,847 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10605
  total_bytes: 10605
}

2022-10-11 03:51:20,949 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10605
  total_bytes: 10605
}

2022-10-11 03:51:21,051 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10605
  total_bytes: 10605
}

2022-10-11 03:51:21,152 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10605
  total_bytes: 10605
}

2022-10-11 03:51:21,254 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10605
  total_bytes: 10605
}

2022-10-11 03:51:21,751 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10605
  total_bytes: 10605
}

2022-10-11 03:51:22,112 INFO    Thread-8  :23483 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10605
  total_bytes: 10605
}
local_info {
}

2022-10-11 03:51:23,693 INFO    Thread-8  :23483 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-10-11 03:51:23,694 INFO    Thread-8  :23483 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-10-11 03:51:23,696 INFO    Thread-8  :23483 [wandb_run.py:_footer_sync_info():2822] logging synced files
