2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'sweep_id': '84yvgh2i', 'run_id': 'yc8oso84', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-84yvgh2i/config-yc8oso84.yaml'}
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_033517-yc8oso84/logs/debug.log
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_033517-yc8oso84/logs/debug-internal.log
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_init.py:init():439] calling init triggers
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 64, 'dropout': 0.5, 'epochs': 1, 'hidden_size': 256, 'learning_rate': 0.0254150824018666, 'optimizer': 'sgd'}
config: {}
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [wandb_init.py:init():492] starting backend
2022-10-11 03:35:17,492 INFO    Thread-2  :18236 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 03:35:17,510 INFO    Thread-2  :18236 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 03:35:17,524 INFO    Thread-2  :18236 [backend.py:ensure_launched():225] started backend process with pid: 18303
2022-10-11 03:35:17,525 INFO    Thread-2  :18236 [wandb_init.py:init():501] backend started and connected
2022-10-11 03:35:17,535 INFO    Thread-2  :18236 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 64, 'dropout': 0.5, 'epochs': 1, 'hidden_size': 256, 'learning_rate': 0.0254150824018666, 'optimizer': 'sgd'}
2022-10-11 03:35:17,538 INFO    Thread-2  :18236 [wandb_init.py:init():565] updated telemetry
2022-10-11 03:35:17,569 INFO    Thread-2  :18236 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 03:35:18,581 INFO    Thread-2  :18236 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 03:35:18,626 INFO    Thread-2  :18236 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 03:35:18,626 INFO    Thread-2  :18236 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 03:35:21,916 INFO    Thread-2  :18236 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 03:35:21,916 INFO    Thread-2  :18236 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 03:35:21,917 INFO    Thread-2  :18236 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 03:35:21,922 ERROR   Thread-2  :18236 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 03:35:21,923 INFO    Thread-2  :18236 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 03:35:21,925 INFO    Thread-2  :18236 [wandb_run.py:_config_callback():992] config_cb None None {'img_feature_path': 'data/features/visualbert/', 'train_csv_path': 'data/splits/random/memotion_train.csv', 'val_csv_path': 'data/splits/random/memotion_val.csv', 'model_type': 'visualbert', 'model_path': 'uclanlp/visualbert-nlvr2-coco-pre', 'epoch': 100, 'eval_step': 100, 'amp': True, 'output_dir': './tmp', 'checkpoint_step': 100, 'random_seed': 42, 'resume_training': False, 'semi_supervised': False}
2022-10-11 03:35:22,296 INFO    Thread-2  :18236 [wandb_run.py:_config_callback():992] config_cb None None {'output_hidden': 768}
2022-10-11 03:39:19,218 INFO    Thread-2  :18236 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/yc8oso84
2022-10-11 03:39:19,225 INFO    Thread-2  :18236 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 03:39:19,228 INFO    Thread-2  :18236 [wandb_run.py:_restore():1674] restore
2022-10-11 03:39:19,231 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 03:39:19,477 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 03:39:19,867 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 10636
}

2022-10-11 03:39:19,969 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 10636
}

2022-10-11 03:39:20,071 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10636
  total_bytes: 10636
}

2022-10-11 03:39:20,173 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10636
  total_bytes: 10636
}

2022-10-11 03:39:20,275 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10636
  total_bytes: 10636
}

2022-10-11 03:39:20,377 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10636
  total_bytes: 10636
}

2022-10-11 03:39:20,479 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10636
  total_bytes: 10636
}

2022-10-11 03:39:20,581 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10636
  total_bytes: 10636
}

2022-10-11 03:39:21,007 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10636
  total_bytes: 10636
}

2022-10-11 03:39:21,367 INFO    Thread-2  :18236 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10636
  total_bytes: 10636
}
local_info {
}

2022-10-11 03:39:23,016 INFO    Thread-2  :18236 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-10-11 03:39:23,017 INFO    Thread-2  :18236 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-10-11 03:39:23,019 INFO    Thread-2  :18236 [wandb_run.py:_footer_sync_info():2822] logging synced files
