2022-10-11 03:03:13,184 INFO    Thread-12 :13483 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 03:03:13,184 INFO    Thread-12 :13483 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 03:03:13,184 INFO    Thread-12 :13483 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'sweep_id': 'k4hmg086', 'run_id': '55v4awn5', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-k4hmg086/config-55v4awn5.yaml'}
2022-10-11 03:03:13,184 INFO    Thread-12 :13483 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 03:03:13,184 INFO    Thread-12 :13483 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_030313-55v4awn5/logs/debug.log
2022-10-11 03:03:13,184 INFO    Thread-12 :13483 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_030313-55v4awn5/logs/debug-internal.log
2022-10-11 03:03:13,185 INFO    Thread-12 :13483 [wandb_init.py:init():439] calling init triggers
2022-10-11 03:03:13,185 INFO    Thread-12 :13483 [wandb_init.py:init():443] wandb.init called with sweep_config: {'amp': True, 'batch_size': 248, 'dropout': 0.5, 'epochs': 1, 'eval_step': 100, 'hidden_size': 256, 'img_feature_path': 'data/features/visualbert/', 'learning_rate': 0.057150346007714584, 'model_path': 'uclanlp/visualbert-nlvr2-coco-pre', 'model_type': 'visualbert', 'optimizer': 'adam', 'output_dir': './tmp', 'random_seed': 42, 'resume_training': True, 'semi-supervised': True, 'train_csv_path': 'data/splits/random/memotion_train.csv', 'val_csv_path': 'val_csv_path'}
config: {}
2022-10-11 03:03:13,185 INFO    Thread-12 :13483 [wandb_init.py:init():487] wandb.init() called when a run is still active
2022-10-11 03:03:13,185 INFO    Thread-12 :13483 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/yqa8bm0m
2022-10-11 03:03:13,185 INFO    Thread-12 :13483 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 03:03:13,187 INFO    Thread-12 :13483 [wandb_run.py:_restore():1674] restore
2022-10-11 03:03:15,588 INFO    Thread-12 :13483 [wandb_run.py:_restore():1674] restore
2022-10-11 03:03:20,796 ERROR   Thread-12 :13483 [wandb_run.py:_atexit_cleanup():1723] Problem finishing run
Traceback (most recent call last):
  File "/content/SSLMemes/src/train.py", line 156, in train
    model_type = config.model_type
AttributeError: 'dict' object has no attribute 'model_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1711, in _atexit_cleanup
    self._on_finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1811, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1751, in _console_stop
    self._restore()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1680, in _restore
    self._err_redir.uninstall()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 754, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 667, in remove_fd
    self._unregister()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 655, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
