2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'sweep_id': 'uhu1kilc', 'run_id': 'tgdne35w', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-uhu1kilc/config-tgdne35w.yaml'}
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_042738-tgdne35w/logs/debug.log
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_042738-tgdne35w/logs/debug-internal.log
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_init.py:init():439] calling init triggers
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 56, 'dropout': 0.5, 'epochs': 1, 'hidden_size': 512, 'learning_rate': 0.022553932710622795, 'optimizer': 'adam'}
config: {}
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [wandb_init.py:init():492] starting backend
2022-10-11 04:27:38,630 INFO    Thread-2  :28710 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 04:27:38,646 INFO    Thread-2  :28710 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 04:27:38,657 INFO    Thread-2  :28710 [backend.py:ensure_launched():225] started backend process with pid: 28743
2022-10-11 04:27:38,659 INFO    Thread-2  :28710 [wandb_init.py:init():501] backend started and connected
2022-10-11 04:27:38,668 INFO    Thread-2  :28710 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 56, 'dropout': 0.5, 'epochs': 1, 'hidden_size': 512, 'learning_rate': 0.022553932710622795, 'optimizer': 'adam'}
2022-10-11 04:27:38,670 INFO    Thread-2  :28710 [wandb_init.py:init():565] updated telemetry
2022-10-11 04:27:38,700 INFO    Thread-2  :28710 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 04:27:39,632 INFO    Thread-2  :28710 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 04:27:39,668 INFO    Thread-2  :28710 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 04:27:39,668 INFO    Thread-2  :28710 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 04:27:42,386 INFO    Thread-2  :28710 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 04:27:42,387 INFO    Thread-2  :28710 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 04:27:42,387 INFO    Thread-2  :28710 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 04:27:42,388 ERROR   Thread-2  :28710 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 04:27:42,390 INFO    Thread-2  :28710 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 04:27:42,390 INFO    Thread-2  :28710 [wandb_run.py:_config_callback():992] config_cb None None {'img_feature_path': 'data/features/visualbert/', 'train_csv_path': 'data/splits/random/memotion_train.csv', 'val_csv_path': 'data/splits/random/memotion_val.csv', 'model_type': 'visualbert', 'model_path': 'uclanlp/visualbert-nlvr2-coco-pre', 'eval_step': 100, 'amp': True, 'output_dir': './tmp', 'checkpoint_step': 100, 'random_seed': 42, 'resume_training': False, 'semi_supervised': True}
2022-10-11 04:27:42,769 INFO    Thread-2  :28710 [wandb_run.py:_config_callback():992] config_cb None None {'output_hidden': 768}
2022-10-11 04:27:48,173 INFO    Thread-2  :28710 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/tgdne35w
2022-10-11 04:27:48,174 INFO    Thread-2  :28710 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 04:27:48,175 INFO    Thread-2  :28710 [wandb_run.py:_restore():1674] restore
2022-10-11 04:27:48,181 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 04:27:48,436 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 04:27:48,647 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 10102
}

2022-10-11 04:27:48,749 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 10102
}

2022-10-11 04:27:48,850 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10102
  total_bytes: 10102
}

2022-10-11 04:27:48,952 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10102
  total_bytes: 10102
}

2022-10-11 04:27:49,054 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10102
  total_bytes: 10102
}

2022-10-11 04:27:49,156 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10102
  total_bytes: 10102
}

2022-10-11 04:27:49,257 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10102
  total_bytes: 10102
}

2022-10-11 04:27:49,779 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10102
  total_bytes: 10102
}

2022-10-11 04:27:50,131 INFO    Thread-2  :28710 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10102
  total_bytes: 10102
}
local_info {
}

2022-10-11 04:27:51,708 INFO    Thread-2  :28710 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-10-11 04:27:51,708 INFO    Thread-2  :28710 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-10-11 04:27:51,710 INFO    Thread-2  :28710 [wandb_run.py:_footer_sync_info():2822] logging synced files
