2022-10-11 03:48:13,482 INFO    Thread-2  :23483 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 03:48:13,482 INFO    Thread-2  :23483 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 03:48:13,482 INFO    Thread-2  :23483 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'sweep_id': 'ivsfe5pd', 'run_id': '52nq6905', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-ivsfe5pd/config-52nq6905.yaml'}
2022-10-11 03:48:13,482 INFO    Thread-2  :23483 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 03:48:13,483 INFO    Thread-2  :23483 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_034813-52nq6905/logs/debug.log
2022-10-11 03:48:13,483 INFO    Thread-2  :23483 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_034813-52nq6905/logs/debug-internal.log
2022-10-11 03:48:13,483 INFO    Thread-2  :23483 [wandb_init.py:init():439] calling init triggers
2022-10-11 03:48:13,483 INFO    Thread-2  :23483 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 56, 'dropout': 0, 'epochs': 1, 'hidden_size': 256, 'learning_rate': 0.09948436010554228, 'optimizer': 'sgd'}
config: {}
2022-10-11 03:48:13,483 INFO    Thread-2  :23483 [wandb_init.py:init():492] starting backend
2022-10-11 03:48:13,483 INFO    Thread-2  :23483 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 03:48:13,499 INFO    Thread-2  :23483 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 03:48:13,509 INFO    Thread-2  :23483 [backend.py:ensure_launched():225] started backend process with pid: 23516
2022-10-11 03:48:13,511 INFO    Thread-2  :23483 [wandb_init.py:init():501] backend started and connected
2022-10-11 03:48:13,519 INFO    Thread-2  :23483 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 56, 'dropout': 0, 'epochs': 1, 'hidden_size': 256, 'learning_rate': 0.09948436010554228, 'optimizer': 'sgd'}
2022-10-11 03:48:13,522 INFO    Thread-2  :23483 [wandb_init.py:init():565] updated telemetry
2022-10-11 03:48:13,550 INFO    Thread-2  :23483 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 03:48:14,501 INFO    Thread-2  :23483 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 03:48:14,543 INFO    Thread-2  :23483 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 03:48:14,543 INFO    Thread-2  :23483 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 03:48:17,390 INFO    Thread-2  :23483 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 03:48:17,391 INFO    Thread-2  :23483 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 03:48:17,391 INFO    Thread-2  :23483 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 03:48:17,397 ERROR   Thread-2  :23483 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 03:48:17,398 INFO    Thread-2  :23483 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 03:48:17,399 INFO    Thread-2  :23483 [wandb_run.py:_config_callback():992] config_cb None None {'img_feature_path': 'data/features/visualbert/', 'train_csv_path': 'data/splits/random/memotion_train.csv', 'val_csv_path': 'data/splits/random/memotion_val.csv', 'model_type': 'visualbert', 'model_path': 'uclanlp/visualbert-nlvr2-coco-pre', 'eval_step': 100, 'amp': True, 'output_dir': './tmp', 'checkpoint_step': 100, 'random_seed': 42, 'resume_training': False, 'semi_supervised': False}
2022-10-11 03:48:17,766 INFO    Thread-2  :23483 [wandb_run.py:_config_callback():992] config_cb None None {'output_hidden': 768}
2022-10-11 03:49:42,904 INFO    Thread-2  :23483 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/52nq6905
2022-10-11 03:49:42,904 INFO    Thread-2  :23483 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-10-11 03:49:42,906 INFO    Thread-2  :23483 [wandb_run.py:_restore():1674] restore
2022-10-11 03:49:42,910 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 03:49:43,156 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 03:49:43,569 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 9284
}

2022-10-11 03:49:43,671 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 10603
}

2022-10-11 03:49:43,773 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10603
  total_bytes: 10603
}

2022-10-11 03:49:43,874 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10603
  total_bytes: 10603
}

2022-10-11 03:49:43,976 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10603
  total_bytes: 10603
}

2022-10-11 03:49:44,078 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10603
  total_bytes: 10603
}

2022-10-11 03:49:44,180 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10603
  total_bytes: 10603
}

2022-10-11 03:49:44,281 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10603
  total_bytes: 10603
}

2022-10-11 03:49:44,695 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10603
  total_bytes: 10603
}

2022-10-11 03:49:45,061 INFO    Thread-2  :23483 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 10603
  total_bytes: 10603
}
local_info {
}

2022-10-11 03:49:46,644 INFO    Thread-2  :23483 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-10-11 03:49:46,644 INFO    Thread-2  :23483 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-10-11 03:49:46,646 INFO    Thread-2  :23483 [wandb_run.py:_footer_sync_info():2822] logging synced files
