2022-10-11 03:18:42,348 INFO    Thread-13 :14974 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 03:18:42,348 INFO    Thread-13 :14974 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 03:18:42,348 INFO    Thread-13 :14974 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'run_id': 'pt4vjc3f', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-k8qp7sz5/config-pt4vjc3f.yaml', 'sweep_id': 'k8qp7sz5'}
2022-10-11 03:18:42,348 INFO    Thread-13 :14974 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 03:18:42,348 INFO    Thread-13 :14974 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_031842-pt4vjc3f/logs/debug.log
2022-10-11 03:18:42,349 INFO    Thread-13 :14974 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_031842-pt4vjc3f/logs/debug-internal.log
2022-10-11 03:18:42,349 INFO    Thread-13 :14974 [wandb_init.py:init():439] calling init triggers
2022-10-11 03:18:42,349 INFO    Thread-13 :14974 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 120, 'dropout': 0.3, 'epochs': 1, 'hidden_size': 128, 'learning_rate': 0.07332331301480909, 'optimizer': 'sgd'}
config: {}
2022-10-11 03:18:42,349 INFO    Thread-13 :14974 [wandb_init.py:init():492] starting backend
2022-10-11 03:18:42,349 INFO    Thread-13 :14974 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 03:18:42,357 INFO    Thread-13 :14974 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 03:18:42,370 INFO    Thread-13 :14974 [backend.py:ensure_launched():225] started backend process with pid: 15503
2022-10-11 03:18:42,373 INFO    Thread-13 :14974 [wandb_init.py:init():501] backend started and connected
2022-10-11 03:18:42,385 INFO    Thread-13 :14974 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 120, 'dropout': 0.3, 'epochs': 1, 'hidden_size': 128, 'learning_rate': 0.07332331301480909, 'optimizer': 'sgd'}
2022-10-11 03:18:42,387 INFO    Thread-13 :14974 [wandb_init.py:init():565] updated telemetry
2022-10-11 03:18:42,412 INFO    Thread-13 :14974 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 03:18:50,037 INFO    Thread-13 :14974 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 03:18:50,117 INFO    Thread-13 :14974 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 03:18:50,118 INFO    Thread-13 :14974 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 03:18:54,637 INFO    Thread-13 :14974 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 03:18:54,638 INFO    Thread-13 :14974 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 03:18:54,638 INFO    Thread-13 :14974 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 03:18:54,639 ERROR   Thread-13 :14974 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 03:18:54,640 INFO    Thread-13 :14974 [wandb_init.py:init():664] run started, returning control to user process
