2022-10-11 04:30:12,815 INFO    Thread-13 :28967 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 04:30:12,815 INFO    Thread-13 :28967 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 04:30:12,815 INFO    Thread-13 :28967 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'run_id': '73bbmw2q', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-4mw8egu9/config-73bbmw2q.yaml', 'sweep_id': '4mw8egu9'}
2022-10-11 04:30:12,815 INFO    Thread-13 :28967 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 04:30:12,816 INFO    Thread-13 :28967 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_043012-73bbmw2q/logs/debug.log
2022-10-11 04:30:12,816 INFO    Thread-13 :28967 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_043012-73bbmw2q/logs/debug-internal.log
2022-10-11 04:30:12,816 INFO    Thread-13 :28967 [wandb_init.py:init():439] calling init triggers
2022-10-11 04:30:12,816 INFO    Thread-13 :28967 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 56, 'dropout': 0.3, 'epochs': 1, 'hidden_size': 256, 'learning_rate': 0.04864721121349255, 'optimizer': 'adam'}
config: {}
2022-10-11 04:30:12,816 INFO    Thread-13 :28967 [wandb_init.py:init():492] starting backend
2022-10-11 04:30:12,817 INFO    Thread-13 :28967 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 04:30:12,827 INFO    Thread-13 :28967 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 04:30:12,873 INFO    Thread-13 :28967 [backend.py:ensure_launched():225] started backend process with pid: 29480
2022-10-11 04:30:12,877 INFO    Thread-13 :28967 [wandb_init.py:init():501] backend started and connected
2022-10-11 04:30:12,901 INFO    Thread-13 :28967 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 56, 'dropout': 0.3, 'epochs': 1, 'hidden_size': 256, 'learning_rate': 0.04864721121349255, 'optimizer': 'adam'}
2022-10-11 04:30:12,910 INFO    Thread-13 :28967 [wandb_init.py:init():565] updated telemetry
2022-10-11 04:30:13,031 INFO    Thread-13 :28967 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 04:30:20,630 INFO    Thread-13 :28967 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 04:30:20,721 INFO    Thread-13 :28967 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 04:30:20,721 INFO    Thread-13 :28967 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 04:30:25,256 INFO    Thread-13 :28967 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 04:30:25,258 INFO    Thread-13 :28967 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 04:30:25,258 INFO    Thread-13 :28967 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 04:30:25,258 ERROR   Thread-13 :28967 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 04:30:25,259 INFO    Thread-13 :28967 [wandb_init.py:init():664] run started, returning control to user process
