2022-10-11 02:53:11,007 INFO    MainThread:12262 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 02:53:11,008 INFO    MainThread:12262 [wandb_setup.py:_flush():75] Loading settings from /content/SSLMemes/wandb/settings
2022-10-11 02:53:11,008 INFO    MainThread:12262 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-10-11 02:53:11,008 INFO    MainThread:12262 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 02:53:11,008 INFO    MainThread:12262 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_025311-3gwohiwp/logs/debug.log
2022-10-11 02:53:11,008 INFO    MainThread:12262 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_025311-3gwohiwp/logs/debug-internal.log
2022-10-11 02:53:11,008 INFO    MainThread:12262 [wandb_init.py:init():439] calling init triggers
2022-10-11 02:53:11,008 INFO    MainThread:12262 [wandb_init.py:init():443] wandb.init called with sweep_config: {}
config: {}
2022-10-11 02:53:11,008 INFO    MainThread:12262 [wandb_init.py:init():492] starting backend
2022-10-11 02:53:11,008 INFO    MainThread:12262 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 02:53:11,023 INFO    MainThread:12262 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 02:53:11,034 INFO    MainThread:12262 [backend.py:ensure_launched():225] started backend process with pid: 12292
2022-10-11 02:53:11,036 INFO    MainThread:12262 [wandb_init.py:init():501] backend started and connected
2022-10-11 02:53:11,045 INFO    MainThread:12262 [wandb_init.py:init():565] updated telemetry
2022-10-11 02:53:11,073 INFO    MainThread:12262 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 02:53:12,071 INFO    MainThread:12262 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 02:53:12,112 INFO    MainThread:12262 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 02:53:12,112 INFO    MainThread:12262 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 02:53:14,985 INFO    MainThread:12262 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 02:53:14,986 INFO    MainThread:12262 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 02:53:14,986 INFO    MainThread:12262 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 02:53:14,993 INFO    MainThread:12262 [wandb_run.py:_redirect():1667] Redirects installed.
2022-10-11 02:53:14,993 INFO    MainThread:12262 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 02:53:15,001 INFO    MainThread:12262 [wandb_settings.py:_apply_settings():1054] Applying settings from <Settings {'_args': None, '_cli_only_mode': None, '_colab': False, '_config_dict': None, '_console': <SettingsConsole.OFF: 0>, '_cuda': None, '_disable_meta': None, '_disable_stats': None, '_disable_viewer': None, '_except_exit': None, '_executable': None, '_internal_check_process': 8, '_internal_queue_timeout': 2, '_jupyter': False, '_jupyter_name': None, '_jupyter_path': None, '_jupyter_root': None, '_kaggle': False, '_noop': False, '_offline': False, '_os': None, '_platform': 'linux', '_python': None, '_require_service': None, '_runqueue_item_id': None, '_save_requirements': True, '_service_transport': None, '_start_datetime': None, '_start_time': None, '_tmp_code_dir': '/content/SSLMemes/wandb/run-None-None/tmp/code', '_tracelog': None, '_unsaved_keys': None, '_windows': False, 'allow_val_change': None, 'anonymous': None, 'api_key': '***REDACTED***', 'base_url': 'https://api.wandb.ai', 'code_dir': None, 'config_paths': None, 'console': 'off', 'deployment': 'cloud', 'disable_code': None, 'disable_git': None, 'disabled': False, 'docker': None, 'email': None, 'entity': None, 'files_dir': '/content/SSLMemes/wandb/run-None-None/files', 'force': None, 'git_remote': 'origin', 'heartbeat_seconds': 30, 'host': None, 'ignore_globs': (), 'is_local': False, 'label_disable': None, 'launch': None, 'launch_config_path': None, 'log_dir': '/content/SSLMemes/wandb/run-None-None/logs', 'log_internal': '/content/SSLMemes/wandb/run-None-None/logs/debug-internal.log', 'log_symlink_internal': '/content/SSLMemes/wandb/debug-internal.log', 'log_symlink_user': '/content/SSLMemes/wandb/debug.log', 'log_user': '/content/SSLMemes/wandb/run-None-None/logs/debug.log', 'login_timeout': None, 'magic': None, 'mode': 'online', 'notebook_name': None, 'problem': 'fatal', 'program': None, 'program_relpath': None, 'project': None, 'project_url': '', 'quiet': None, 'reinit': None, 'relogin': None, 'resume': None, 'resume_fname': '/content/SSLMemes/wandb/wandb-resume.json', 'resumed': False, 'root_dir': '/content/SSLMemes', 'run_group': None, 'run_id': None, 'run_job_type': None, 'run_mode': 'run', 'run_name': None, 'run_notes': None, 'run_tags': None, 'run_url': '', 'sagemaker_disable': None, 'save_code': None, 'settings_system': '/root/.config/wandb/settings', 'settings_workspace': '/content/SSLMemes/wandb/settings', 'show_colors': None, 'show_emoji': None, 'show_errors': True, 'show_info': True, 'show_warnings': True, 'silent': False, 'start_method': None, 'strict': None, 'summary_errors': None, 'summary_warnings': 5, 'sweep_id': None, 'sweep_param_path': None, 'sweep_url': '', 'symlink': None, 'sync_dir': '/content/SSLMemes/wandb/run-None-None', 'sync_file': '/content/SSLMemes/wandb/run-None-None/run-None.wandb', 'sync_symlink_latest': '/content/SSLMemes/wandb/latest-run', 'system_sample': 15, 'system_sample_seconds': 2, 'timespec': None, 'tmp_dir': '/content/SSLMemes/wandb/run-None-None/tmp', 'username': None, 'wandb_dir': '/content/SSLMemes/wandb/'}>
2022-10-11 02:53:15,007 INFO    MainThread:12262 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 02:53:15,007 INFO    MainThread:12262 [wandb_setup.py:_flush():75] Loading settings from /content/SSLMemes/wandb/settings
2022-10-11 02:53:15,007 INFO    MainThread:12262 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-10-11 02:53:15,007 INFO    MainThread:12262 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 02:53:15,008 INFO    MainThread:12262 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_025315-6epxjwco/logs/debug.log
2022-10-11 02:53:15,008 INFO    MainThread:12262 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_025315-6epxjwco/logs/debug-internal.log
2022-10-11 02:53:15,008 INFO    MainThread:12262 [wandb_init.py:init():439] calling init triggers
2022-10-11 02:53:15,008 INFO    MainThread:12262 [wandb_init.py:init():443] wandb.init called with sweep_config: {}
config: {}
2022-10-11 02:53:15,008 INFO    MainThread:12262 [wandb_init.py:init():487] wandb.init() called when a run is still active
2022-10-11 02:53:16,017 INFO    MainThread:12262 [pyagent.py:run():320] Starting sweep agent: entity=None, project=None, count=5
2022-10-11 02:53:16,853 INFO    Thread-12 :12262 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 02:53:16,853 INFO    Thread-12 :12262 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 02:53:16,854 INFO    Thread-12 :12262 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'sweep_id': 'x1uex3wq', 'run_id': 'ng1ocqpk', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-x1uex3wq/config-ng1ocqpk.yaml'}
2022-10-11 02:53:16,854 INFO    Thread-12 :12262 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 02:53:16,854 INFO    Thread-12 :12262 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_025316-ng1ocqpk/logs/debug.log
2022-10-11 02:53:16,854 INFO    Thread-12 :12262 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_025316-ng1ocqpk/logs/debug-internal.log
2022-10-11 02:53:16,854 INFO    Thread-12 :12262 [wandb_init.py:init():439] calling init triggers
2022-10-11 02:53:16,854 INFO    Thread-12 :12262 [wandb_init.py:init():443] wandb.init called with sweep_config: {'amp': True, 'batch_size': 168, 'dropout': 0.3, 'epochs': 1, 'eval_step': 100, 'hidden_size': 128, 'img_feature_path': 'data/features/visualbert/', 'learning_rate': 0.026868732379981875, 'model_path': 'uclanlp/visualbert-nlvr2-coco-pre', 'model_type': 'visualbert', 'optimizer': 'adam', 'output_dir': './tmp', 'random_seed': 42, 'resume_training': True, 'semi-supervised': True, 'train_csv_path': 'data/splits/random/memotion_train.csv', 'val_csv_path': 'val_csv_path'}
config: {}
2022-10-11 02:53:16,854 INFO    Thread-12 :12262 [wandb_init.py:init():487] wandb.init() called when a run is still active
2022-10-11 02:53:16,854 INFO    Thread-12 :12262 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/3gwohiwp
2022-10-11 02:53:16,855 INFO    Thread-12 :12262 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 02:53:16,857 INFO    Thread-12 :12262 [wandb_run.py:_restore():1674] restore
2022-10-11 02:53:19,032 INFO    Thread-12 :12262 [wandb_run.py:_restore():1674] restore
2022-10-11 02:53:21,804 ERROR   Thread-12 :12262 [wandb_run.py:_atexit_cleanup():1723] Problem finishing run
Traceback (most recent call last):
  File "/content/SSLMemes/src/train.py", line 154, in train
    model_type = config.model_type
AttributeError: 'NoneType' object has no attribute 'model_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1711, in _atexit_cleanup
    self._on_finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1811, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1751, in _console_stop
    self._restore()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1680, in _restore
    self._err_redir.uninstall()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 754, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 667, in remove_fd
    self._unregister()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 655, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
