Some weights of the model checkpoint at uclanlp/visualbert-nlvr2-coco-pre were not used when initializing VisualBertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing VisualBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing VisualBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/content/SSLMemes/src/train.py", line 241, in <module>
    train(config=config,args=args)
  File "/content/SSLMemes/src/train.py", line 179, in train
    model,tokenizer,processor = create_model(config,model_type)
  File "/content/SSLMemes/src/utils.py", line 25, in create_model
    model = ModelForBinaryClassification(cfg,model,num_label=4)
  File "/content/SSLMemes/src/model.py", line 13, in __init__
    self.ff = nn.Sequential(nn.Linear(output_hidden,cfg.hidden_size),nn.Dropout(cfg.dropout),nn.Linear(cfg.hidden_size,self.num_label))
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_config.py", line 131, in __getitem__
    return self._items[key]
KeyError: 'hidden_size'